errloc: 04_errorlocalization.Rmd
	R -e 'rmarkdown::render("04_errorlocalization.Rmd")'


imputation: 05_imputation.Rmd
	R -e 'rmarkdown::render("05_imputation.Rmd")'

adjust: 06_adjusting.Rmd
	R -e 'rmarkdown::render("06_adjusting.Rmd")'

monitoring: 07_monitoring.Rmd
	R -e 'rmarkdown::render("07_monitoring.Rmd")'


