raw: 01_raw_to_input.Rmd
	R -e 'rmarkdown::render("01_raw_to_input.Rmd")'


matching: 02_matching.Rmd
	R -e 'rmarkdown::render("02_matching.Rmd")'


validation: 03_validation.Rmd
	R -e 'rmarkdown::render("03_validation.Rmd")'


