
all: valuechain.tex vc_raw.tex
	pdflatex valuechain.tex
	pdflatex vc_raw.tex
	pdflatex vc_input.tex
	pdflatex vc_valid.tex
	pdflatex vc_statistics.tex
	pdflatex vc_format.tex


clean:
	rm -f *.log
	rm -f *.aux
